import Head from "next/head";

import { LayoutProps } from "./interface";
import Footer from "../footer";
import Navbar from "../navbar";

const Layout = (props: LayoutProps) => {
  const { children, socialMedia } = props;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
      <Footer socialMedia={socialMedia} />
    </div>
  );
};

export default Layout;
