cms_manual_init: true

backend:
  name: github
  repo: claudioquirozipi/cquirozipi
  branch: main

media_folder: "public/img"
public_folder: "img"
logo_url: "https://deluxe-sfogliatella-257244.netlify.app/vercel.svg"
locale: es

collections:
  - name: home
    label: Home
    label_singular: Home
    description: redes sociales, del portafolio
    create: true
    folder: content/home
    slug: "{{title}}"
    fields:
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Imagen", name: "home_image", widget: "image" }
      - { label: "Descripción", name: "description", widget: "markdown" }
      - { label: "Link", name: "url", widget: "string" }
  - name: certificates
    label: Certificados
    label_singular: Certificado
    description: redes sociales, del portafolio
    create: true
    folder: content/certificates
    slug: "{{title}}"
    fields:
      - { label: "Certificado", name: "title", widget: "string" }
      - { label: "Imagen", name: "certificates_image", widget: "image" }
      - { label: "Descripción", name: "description", widget: "markdown" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - label: "Insituto"
        name: "institute"
        widget: "select"
        default: ""
        options:
          - { label: "otro", value: "" }
          - { label: "Platzi", value: "platzi" }
          - { label: "Udemy", value: "udemy" }
          - { label: "ED-team", value: "edteam" }
          - { label: "NttData", value: "nttdata" }
  - name: technologies
    label: Tecnologías
    label_singular: Tecnología
    description: redes sociales, del portafolio
    create: true
    folder: content/technologies
    slug: "{{title}}"
    fields:
      - { label: "Tecnología", name: "title", widget: "string" }
      - { label: "Imagen", name: "technology_image", widget: "image" }
  - name: Projects
    label: Proyectos
    label_singular: proyecto
    description: redes sociales, del portafolio
    create: true
    folder: content/projects
    slug: "{{title}}"
    fields:
      - { label: "Proyecto", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "markdown" }
      - { label: "Imagen", name: "project_image", widget: "image" }
      - { label: "urlWeb", name: "urlWeb", widget: "string" }
      - { label: "urlGithub", name: "urlGithub", widget: "string" }
    img: tracsa,
  - name: social_media
    label: Redes sociales
    label_singular: red social
    description: redes sociales, del portafolio
    create: true
    folder: content/social_media
    slug: "{{title}}"
    fields:
      - { label: "Red social", name: "title", widget: "string" }
      - { label: "Imagen", name: "social_media_image", widget: "image" }
      - { label: "Link", name: "url", widget: "string" }
